name: test and deploy project
on:
    push:
        branches: [ "final/usingCustomWorkflow" ]
    workflow_dispatch:
jobs:
    compile-and-test:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: install node dependencies
              run: npm ci
            - name: run tests
              run: npm test
        

        